# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kegal Timer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kegal Timer
pod 'JTAppleCalendar', '7.1.6'
pod 'SwiftEntryKit', '1.0.1'
pod 'Google-Mobile-Ads-SDK'
pod 'FBAudienceNetwork'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'

  target 'Kegal TimerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Kegal TimerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
